// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var MissingBasicComponentConstructor = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.MissingBasicComponentConstructor");

var MissingComponentConstructor = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.MissingComponentConstructor");

var MissingMemoComponentConstructor = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.MissingMemoComponentConstructor");

var MissingMemoBasicComponentConstructor = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.MissingMemoBasicComponentConstructor");

var OutOfContextHookCall = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.OutOfContextHookCall");

var IncompatibleHook = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.IncompatibleHook");

var MissingContext = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.MissingContext");

var DesyncContextValue = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.DesyncContextValue");

var UnboundContextInstance = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.UnboundContextInstance");

var InvalidHostConstructor = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.InvalidHostConstructor");

var MissingWorkInProgressRoot = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.MissingWorkInProgressRoot");

var MissingCurrentRoot = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.MissingCurrentRoot");

var Component = /* @__PURE__ */Caml_exceptions.create("Exceptions-ReView.Component");

exports.MissingBasicComponentConstructor = MissingBasicComponentConstructor;
exports.MissingComponentConstructor = MissingComponentConstructor;
exports.MissingMemoComponentConstructor = MissingMemoComponentConstructor;
exports.MissingMemoBasicComponentConstructor = MissingMemoBasicComponentConstructor;
exports.OutOfContextHookCall = OutOfContextHookCall;
exports.IncompatibleHook = IncompatibleHook;
exports.MissingContext = MissingContext;
exports.DesyncContextValue = DesyncContextValue;
exports.UnboundContextInstance = UnboundContextInstance;
exports.InvalidHostConstructor = InvalidHostConstructor;
exports.MissingWorkInProgressRoot = MissingWorkInProgressRoot;
exports.MissingCurrentRoot = MissingCurrentRoot;
exports.Component = Component;
/* No side effect */
